

CREATE TABLE IF NOT EXISTS DemoTest (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
   aadhar BIGINT NOT NULL,
  amount  DOUBLE DEFAULT NULL
);
